# Generated by Django 4.1.5 on 2023-01-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('mu_id', models.AutoField(primary_key=True, serialize=False)),
                ('mu_musica', models.CharField(max_length=100, verbose_name='Música')),
                ('mu_autor', models.CharField(max_length=100, verbose_name='Autor/Compositor')),
                ('mu_interprete', models.CharField(max_length=100, verbose_name='Intérprete/Cantor')),
            ],
        ),
    ]
