# Generated by Django 4.1.5 on 2023-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='mu_capa',
            field=models.CharField(default='default', max_length=500, verbose_name='Link da Capa'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='mu_autor',
            field=models.CharField(default='default', max_length=100, verbose_name='Autor/Compositor'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='mu_interprete',
            field=models.CharField(default='default', max_length=100, verbose_name='Intérprete/Cantor'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='mu_musica',
            field=models.CharField(default='default', max_length=100, verbose_name='Música'),
        ),
    ]
