# Generated by Django 4.1.4 on 2023-01-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listagem', '0002_musica_mu_capa_alter_musica_mu_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='mu_autor',
            field=models.CharField(max_length=100, verbose_name='Autor/Compositor'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='mu_capa',
            field=models.CharField(max_length=500, verbose_name='Link da Capa'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='mu_interprete',
            field=models.CharField(max_length=100, verbose_name='Intérprete/Cantor'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='mu_musica',
            field=models.CharField(max_length=100, verbose_name='Música'),
        ),
    ]
